name: CVC5 Coverage Daily Check

on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * *"

jobs:
  check:
    uses: ./.github/workflows/solver-coverage-daily-check.yml
    with:
      solver_name: cvc5
      contract_path: contracts/solvers/cvc5.yml
    secrets: inherit
