name: CVC5 Manager

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: "Optional: Commit hash to add to build queue"
        required: false
        type: string
  schedule:
    - cron: "15 0,6,12,18 * * *"

jobs:
  manager:
    uses: ./.github/workflows/solver-manager.yml
    with:
      solver_name: cvc5
      contract_path: contracts/solvers/cvc5.yml
      commit_hash: ${{ inputs.commit_hash }}
    secrets: inherit
