name: OpenSMT Coverage Daily Check

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

jobs:
  check:
    uses: ./.github/workflows/solver-coverage-daily-check.yml
    with:
      solver_name: opensmt
      contract_path: contracts/solvers/opensmt.yml
    secrets: inherit
